# Generated by Django 4.0.1 on 2022-01-17 10:58

from django.db import migrations

from products.gen_master_data import gen_master


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='ProductCategoryItem',
        ),
        migrations.RunPython(gen_master),
    ]
