# Generated by Django 4.0.1 on 2022-01-17 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_productcategory_productcategoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategoryitem',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategoryitem',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='갱신날짜'),
        ),
    ]
