# Generated by Django 4.0.1 on 2022-01-17 11:09

from django.db import migrations

from products.gen_master_data import gen_master


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0003_productcategoryitem_reg_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='cate_item',
        ),
        migrations.RunPython(gen_master),
    ]
