# Generated by Django 4.0.1 on 2022-01-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcategoryitem_reg_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='cate_item',
        ),
    ]
