# Generated by Django 4.0.1 on 2022-01-17 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('products', '0004_rename_category_product_cate_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPickedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='갱신날짜')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_picked_users',
            field=models.ManyToManyField(through='products.ProductPickedUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productpickeduser',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='productpickeduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
